// Generated by CoffeeScript 1.9.2
var TODO, debug, error, info, queues, ref;

ref = objective.logger, info = ref.info, error = ref.error, TODO = ref.TODO;

debug = objective.logger.createDebug('queue');

module.exports.queues = queues = {};

module.exports.create = function(name) {
  if (queues[name] != null) {
    throw new Error("Queue '" + name + "' already exists.");
  }
  queues[name] = {
    pending: [],
    enque: function(enqueued) {
      return function() {
        var done, i, inject, queue;
        queue = queues[name];
        queue.pending.push({
          args: arguments,
          fn: enqueued
        });
        debug("queue '" + name + "' enqueued at length " + queue.pending.length);
        done = function() {
          var args, fn, i, inject, ref1;
          queue.pending.shift();
          debug("queue '" + name + "' dequeued to length " + queue.pending.length);
          if (!(queue.pending.length > 0)) {
            return;
          }
          ref1 = queue.pending.shift(), args = ref1.args, fn = ref1.fn;
          inject = [done];
          for (i in args) {
            inject.push(args[i]);
          }
          return fn.apply(null, inject);
        };
        if (queue.pending.length === 1) {
          inject = [done];
          for (i in arguments) {
            inject.push(arguments[i]);
          }
          return enqueued.apply(null, inject);
        }
      };
    }
  };
  return queues[name];
};

module.exports.get = function(name) {
  return queues[name] || module.exports.create(name);
};
