// Generated by CoffeeScript 1.9.2
module.exports.debug = require('debug')('debug');

module.exports.info = require('debug')('info');

module.exports.error = require('debug')('error');

module.exports.TODO = require('debug')('TODO');
