// Generated by CoffeeScript 1.9.2
var Objective, deferred, fs, path, pipeline, program, ref, required, uuid;

ref = require('also'), deferred = ref.deferred, pipeline = ref.pipeline;

path = require('path');

fs = require('fs');

uuid = require('uuid');

required = {};

module.exports = Objective = function(config) {
  var base, count, loadGlobal, moduleName, oldConfig, run, title;
  if (config == null) {
    config = {};
  }
  if (typeof config === 'string') {
    title = config;
    config = arguments[1] || {};
    config.title = title;
  }
  if (objective.root != null) {
    (base = objective.root).children || (base.children = {});
    if (objective.root.children[config.uuid] != null) {
      oldConfig = objective.root.children[config.uuid].root;
      console.log("Updating '" + config.title + "' from '" + oldConfig.filename + "'");
      config.filename = oldConfig.filename;
      objective.root.children[config.uuid] = {
        root: config
      };
      objective.root.children[config.uuid].doRun = true;
    } else {
      config.filename = objective.loading;
      console.log("Loading '" + config.title + "' from '" + config.filename + "'");
      objective.root.children[config.uuid] = {
        root: config
      };
    }
    return {
      run: function(fn) {
        var e, moduleFile, name, running;
        objective.root.children[config.uuid].run = fn;
        if (program.run || objective.root.children[config.uuid].doRun) {
          for (moduleFile in require.cache) {
            if (required[moduleFile]) {
              continue;
            }
            delete require.cache[moduleFile];
          }
          console.log("Running '" + config.title + "' from '" + config.filename + "'");
          try {
            for (name in objective.plugins) {
              try {
                objective.plugins[name].before(config);
              } catch (_error) {}
            }
            running = fn();
            if ((running != null) && typeof running.then === 'function') {
              running.then(function(result) {
                return console.log({
                  result: result
                });
              }, function(error) {
                return console.log({
                  error: error
                });
              }, function(notify) {
                return console.log({
                  notify: notify
                });
              });
              if (typeof running.start === 'function') {
                return running.start();
              }
            }
          } catch (_error) {
            e = _error;
            return console.log(e.stack + '\n');
          }
        }
      }
    };
  }
  objective.root = config;
  run = function(e) {
    console.log('Missing .run(fn)');
    if (e != null) {
      return console.log(e.toString());
    }
  };
  loadGlobal = function(name, path) {
    if (objective[name] != null) {
      console.log("Warning: global " + name + " no loaded.");
      return;
    }
    objective[name] = require(path);
    if (name === 'coffee') {
      return objective.coffee.register();
    }
  };
  loadGlobal('recurse', './globals/recurse');
  loadGlobal('coffee', 'coffee-script');
  loadGlobal('uplink', './globals/uplink');
  loadGlobal('prompt', './globals/prompt');
  loadGlobal('pipe', './globals/pipeline');
  config.plugins || (config.plugins = []);
  objective.plugins || (objective.plugins = {});
  count = 1;
  pipeline((function() {
    var j, len, ref1, results;
    ref1 = config.plugins;
    results = [];
    for (j = 0, len = ref1.length; j < len; j++) {
      moduleName = ref1[j];
      results.push((function(moduleName) {
        return deferred(function(arg) {
          var camel, e, i, k, name, p, parts, ref2, reject, resolve;
          resolve = arg.resolve, reject = arg.reject;
          if (typeof moduleName !== 'string') {
            if (!moduleName.name) {
              moduleName.name = "plugin" + (count++);
              console.log("Warning: Plugin without name. (set .name property)");
            }
            if (global[moduleName.name] != null) {
              return reject(new Error("Plugin " + moduleName + " collides with global." + moduleName.name));
            }
            console.log("Loading plugin '" + moduleName + "' as '" + moduleName.name + "'");
            global[moduleName.name] = moduleName;
            try {
              moduleName.init(function(e) {
                if (e != null) {
                  return reject(e);
                }
                return resolve();
              });
            } catch (_error) {
              e = _error;
              return reject(e);
            }
            return;
          }
          name = moduleName.split(path.sep).pop().replace(/objective-/, '');
          if (name.match(/[-\._]/)) {
            parts = name.split(/[-\._]/);
            camel = parts[0];
            for (i = k = 1, ref2 = parts.length - 1; 1 <= ref2 ? k <= ref2 : k >= ref2; i = 1 <= ref2 ? ++k : --k) {
              p = parts[i][0].toUpperCase();
              camel += p + parts[i].slice(1);
            }
            name = camel;
          }
          if (global[name] != null) {
            return reject(new Error("Plugin " + moduleName + " collides with global." + name));
          }
          try {
            if (moduleName.match(/^\./)) {
              moduleName = path.normalize(process.cwd() + path.sep + moduleName);
            }
            global[name] = require(moduleName);
          } catch (_error) {
            e = _error;
            return reject(e);
          }
          console.log("Loading plugin '" + moduleName + "' as '" + name + "'");
          try {
            return global[name].init(function(e) {
              if (e != null) {
                return reject(e);
              }
              objective.plugins[name] = global[name];
              return resolve();
            });
          } catch (_error) {
            e = _error;
            return reject(e);
          }
        });
      })(moduleName));
    }
    return results;
  })()).then(function(result) {
    return process.nextTick(function() {
      var dir, filename;
      for (filename in require.cache) {
        required[filename] = {};
      }
      if (program.recurse != null) {
        if (typeof program.recurse !== 'string') {
          console.log("\nRecurse needs [dir]");
          return;
        }
        dir = program.recurse;
        return objective.recurse(dir, function(err) {
          if (err != null) {
            return run(err);
          }
          return run(null);
        });
      }
      if (program.prompt) {
        return objective.prompt();
      }
      return run(null);
    });
  }, function(error) {
    if (program.prompt) {
      return console.log(error.stack);
    }
    return process.nextTick(function() {
      return run(error);
    });
  });
  return {
    run: function(fn) {
      return run = fn;
    }
  };
};

Object.defineProperty(global, 'objective', {
  get: function() {
    return Objective;
  },
  configurable: false
});

program = require('./cli');
