// Generated by CoffeeScript 1.9.2
var fs, program;

fs = require('fs');

program = require('commander');

program.version(JSON.parse(fs.readFileSync(__dirname + '/../package.json')).version).option('-R, --register', 'Register new user.').option('-C, --create', 'Create new objective.').option('-f, --file [file]', 'Specify objective file namepart.').option('-F, --force', 'Force action.').option('-j, --js', 'Use javascript for --create.').parse(process.argv);

console.log('TODO: --refresh-user (json)');

if (program.register) {
  return require('./actions/register')["do"](program, function() {});
}

if (program.create) {
  return require('./actions/create')["do"](program, function() {});
}

require('./actions/run')["do"](program, function() {});
