// Generated by CoffeeScript 1.9.2
var client, fs, socket, user, version;

user = require('./user');

client = require('socket.io-client');

fs = require('fs');

user.load();

socket = void 0;

version = JSON.parse(fs.readFileSync(__dirname + '/../package.json').toString()).version;

module.exports = {
  connect: function(objective, callback) {
    var key;
    key = user.key;
    socket = client('https://ipso.io');
    socket.on('connect_error', function(e) {
      return console.log('connect error', e.toString());
    });
    socket.on('connect_timeout', function() {
      return console.log('timeout');
    });
    socket.on('connect', function() {
      return socket.emit('auth', {
        version: version,
        objective: objective,
        key: key
      });
    });
    socket.on('reconnect', function(n) {
      return console.log('reconnected ' + n);
    });
    socket.on('reconnect_attempt', function() {
      return console.log('reconnect attempt');
    });
    socket.on('reconnecting', function(n) {
      return console.log('reconnecting ' + n);
    });
    socket.on('reconnect_error', function(e) {
      return console.log('reconnect error', e.toString());
    });
    socket.on('reconnect_failed', function() {
      return console.log('reconnect failed after reconnectionAttempts');
    });
    socket.on('auth.good', function(arg) {
      var online_users;
      online_users = arg.online_users;
      console.log("online now: " + (JSON.stringify(online_users)));
      return callback();
    });
    socket.on('auth.bad', function() {
      return callback(new Error('Bad key or objective uuid.'));
    });
    socket.on('auth.err', callback);
    socket.on('auth.banner', function(message) {
      return callback(new Error(message));
    });
    socket.on('user.joined', function(user) {
      return console.log("user joined: " + (JSON.stringify(user)));
    });
    return socket.on('user.left', function(user) {
      return console.log("user left: " + (JSON.stringify(user)));
    });
  },
  disconnect: function() {
    return socket.disconnect();
  }
};
