// Generated by CoffeeScript 1.9.2
var fs;

fs = require('fs');

module.exports = {
  load: function() {
    var e, email, key, ref, username;
    try {
      ref = JSON.parse(fs.readFileSync(process.env.HOME + '/.objective/user.json')), username = ref.username, email = ref.email, key = ref.key;
      module.exports.username = username;
      module.exports.email = email;
      return module.exports.key = key;
    } catch (_error) {
      e = _error;
      if (e.errno === 34) {
        console.log("\nMissing user.\n\n--register (To create one)\n--offline  (To not need one)\n\nSee: https://ipso.io\n");
        process.exit(1);
      }
      return console.log(e.toString());
    }
  }
};
