// Generated by CoffeeScript 1.9.2
var SomethingClassy;

module.exports = SomethingClassy = (function() {
  function SomethingClassy(name) {
    this.name = name;
    this.flashyCar = 'wife got a poodle?';
    this.eatInterval = setInterval(((function(_this) {
      return function() {
        return _this.eat();
      };
    })(this)), 500);
  }

  SomethingClassy.prototype.eat = function() {};

  SomethingClassy.prototype.work = function() {};

  SomethingClassy.prototype.sit = function() {
    return '-h--';
  };

  SomethingClassy.prototype.sleep = function() {
    return "goodnight " + this.name;
  };

  SomethingClassy.rushHour = function() {};

  return SomethingClassy;

})();
